name: hughes-min

channels:
  - defaults

dependencies:
  - numpy=1.18.1
  - pip=20.0.2
  - scikit-image=0.15.0
  - scipy=1.4.1
  - setuptools=41.4.0
  - pip:
    - meshio==4.0.6
    - treelog==1.0b5
    - stringly==1.0b1
    - typing-extensions==3.7.4.2
    - nutils==6.0
